import random
import time
places = ['ANDRA PRADESH', 'HYDERABAD', 'AMARAVATI', 'ARUNACHAL PRADESH', 'ITANGAR', 'ASSAM', 'DISPUR', 'BIHAR', 'PATNA', 'CHHATTISGARH', 'RAIPUR', 'GOA', 'PANAJI', 'GUJARAT', 'GANDHINAGAR', 'HARYANA', 'CHANDIGARH', 'HIMACHAL PRADESH', 'SHIMLA', 'JAMMU', 'KASHMIR', 'SRINAGAR', 'JAMMU', 'JHARKHAND', 'RANCHI', 'KARNATAKA', 'BANGALORE', 'KERALA', 'THIRUVANANTHAPURAM', 'MADYA PRADESH', 'BHOPAL', 'MAHARASHTRA', 'MUMBAI', 'MANIPUR', 'IMPHAL', 'MEGHALAYA', 'SHILLONG', 'MIZORAM', 'AIZAWI', 'NAGALAND', 'KOHIMA', 'ORISSA', 'BHUBANESHWAR', 'PUNJAB', 'CHANDIGARH', 'RAJASTHAN', 'JAIPUR', 'SIKKIM', 'GANGTOK', 'TAMIL NADU', 'CHENNAI', 'TELAGANA', 'HYDERABAD', 'TRIPURA', 'AGARTALA', 'UTTARANCHAL', 'DEHRADUN', 'UTTAR PRADESH', 'LUCKNOW', 'WEST BENGAL', 'KOLKATA', 'ANDAMAN AND NICOBAR ISLANDS', 'PORT BLAIR', 'CHANDIGARH', 'CHANDIGARH', 'DADAR AND NAGAR HAVELI', 'SILVASSA', 'DAMAN AND DIU', 'DAMAN', 'DELHI', 'LAKSHADEEP', 'KAVARATTI', 'PONDICHERRY','AFGHANISTAN', 'KABUL', 'ALBANIA', 'TIRANA', 'ALGERIA', 'ALGIERS', 'ANDORRA', 'ANDORRA', 'LA VELLA', 'ANGOLA', 'LUANDA', 'ANTIGUA & BARBUDA', "SAINT JOHN'S", 'ARGENTINA', 'BUENOS', 'AIRES', 'ARMENIA', 'YEREVAN', 'AUSTRALIA', 'CANBERRA', 'AUSTRIA', 'VIENNA', 'AZERBAIJAN', 'BAKU', 'BAHAMAS', 'NASSAU', 'BAHRAIN', 'MANAMA', 'BANGLADESH', 'DHAKA', 'BARBADOS', 'BRIDGETOWN', 'BELARUS', 'MINSK', 'BELGIUM', 'BRUSSELS', 'BELIZE', 'BELMOPAN', 'BENIN', 'PORTO-NOVO', 'BHUTAN', 'THIMPHU', 'BOLIVIA', 'SUCRE', 'BOSNIA & HERZEGOVINA', 'SARAJEVO', 'BOTSWANA', 'GABORONE', 'BRAZIL', 'BRASILIA', 'BRUNEI', 'BANDAR SERI BEGAWAN', 'BULGARIA', 'SOFIA', 'BURKINA', 'FASO', 'OUAGADOUGOU', 'BURUNDI', 'BUJUMBURA', 'CABO VERDE', 'PRAIA', 'CAMBODIA', 'PHNOM PENH', 'CAMEROON', 'YAOUNDE', 'CANADA', 'OTTAWA', 'CENTRAL AFRICAN REPUBLIC', 'BANGUI', 'CHAD', "N'DJAMENA", 'CHILE', 'SANTIAGO', 'CHINA', 'BEIJING', 'COLOMBIA', 'BOGOTÁ', 'COMOROS', 'MORONI', 'CONGO', 'DEMOCRATIC REPUBLIC OF THE KINSHASA', 'COSTA RICA', 'SAN JOSE', "CÔTE D'IVOIRE", 'YAMOUSSOUKRO', 'CROATIA', 'ZAGREB', 'CUBA', 'HAVANA', 'CYPRUS', 'NICOSIA', 'CZECH', 'PRAGUE', 'DENMARK', 'COPENHAGEN', 'DJIBOUTI', 'DOMINICA', 'ROSEAU', 'DOMINICAN REPUBLIC', 'SANTO', 'DOMINGO', 'ECUADOR', 'QUITO', 'EGYPT', 'CAIRO', 'EL SALVADOR', 'SAN SALVADOR', 'EQUATORIAL', 'GUINEA', 'MALABO', 'ERITREA', 'ASMARA', 'ESTONIA', 'TALLINN', 'ESWATINI', 'MBABANE', 'ETHIOPIA', 'ADDIS ABABA', 'FEDERATED STATES OF MICRONESIA\tPALIKIR', 'FIJI', 'SUVA', 'FINLAND', 'HELSINKI', 'FRANCE', 'PARIS', 'GABON', 'LIBREVILLE', 'GAMBIA', 'BANJUL', 'GEORGIA', 'TBILISI', 'GERMANY', 'BERLIN', 'GHANA', 'ACCRA', 'GREECE', 'ATHENS', 'GRENADA', "SAINT GEORGE'S", 'GUATEMALA', 'GUATEMALA CITY', 'GUINEA', 'CONAKRY', 'GUINEA-BISSAU', 'BISSAU', 'GUYANA', 'GEORGETOWN', 'HAITI', 'PORT-AU-PRINCE', 'HONDURAS', 'TEGUCIGALPA', 'HUNGARY', 'BUDAPEST', 'ICELAND', 'REYKJAVIK', 'INDIA', 'NEW DELHI', 'INDONESIA', 'JAKARTA', 'IRAN', 'TEHRAN', 'IRAQ', 'BAGHDAD', 'IRELAND', 'DUBLIN', 'ISRAEL', 'JERUSALEM', 'ITALY', 'ROME', 'JAMAICA', 'KINGSTON', 'JAPAN', 'TOKYO', 'JORDAN', 'AMMAN', 'KAZAKHSTAN', 'NUR-SULTAN', 'KENYA', 'NAIROBI', 'KIRIBATI', 'SOUTH TARAWA', 'KOSOVO', 'PRISTINA', 'KUWAIT', 'KUWAIT CITY', 'KYRGYZSTAN', 'BISHKEK', 'LAOS', 'VIENTIANE', 'LATVIA', 'RIGA', 'LEBANON', 'BEIRUT', 'LESOTHO', 'MASERU', 'LIBERIA', 'MONROVIA', 'LIBYA', 'TRIPOLI', 'LIECHTENSTEIN', 'VADUZ', 'LITHUANIA', 'VILNIUS', 'LUXEMBOURG', 'LUXEMBOURG', 'MADAGASCAR', 'ANTANANARIVO', 'MALAWI', 'LILONGWE', 'MALAYSIA', 'KUALA LUMPUR', 'MALDIVES', 'MALE', 'MALI', 'BAMAKO', 'MALTA', 'VALLETTA', 'MARSHALL ISLANDS', 'MAJURO', 'MAURITANIA', 'NOUAKCHOTT', 'MAURITIUS', 'PORT LOUIS', 'MEXICO', 'MEXICO CITY', 'MOLDOVA', 'CHISINAU', 'MONACO', 'MONACO', 'MONGOLIA', 'ULAANBAATAR', 'MONTENEGRO', 'PODGORICA', 'MOROCCO', 'RABAT', 'MOZAMBIQUE', 'MAPUTO', 'MYANMAR', 'NAY PYI TAW', 'NAMIBIA', 'WINDHOEK', 'NAURU', 'YAREN DISTRICT', 'NEPAL', 'KATHMANDU', 'NETHERLANDS', 'AMSTERDAM', 'NEW ZEALAND', 'WELLINGTON', 'NICARAGUA', 'MANAGUA', 'NIGER', 'NIAMEY', 'NIGERIA', 'ABUJA', 'NORTH KOREA', 'PYONGYANG', 'NORTH MACEDONIA', 'SKOPJE', 'NORWAY', 'OSLO', 'OMAN', 'MUSCAT', 'PAKISTAN', 'ISLAMABAD', 'PALAU', 'NGERULMUD', 'PALESTINE', 'EAST JERUSALEM', 'PANAMA', 'PANAMA CITY', 'PAPUA NEW GUINEA', 'PORT MORESBY', 'PARAGUAY', 'ASUNCION', 'PERU', 'LIMA', 'PHILIPPINES', 'MANILA', 'POLAND', 'WARSAW', 'PORTUGAL', 'LISBON', 'QATAR', 'DOHA', 'REPUBLIC OF THE CONGO', 'BRAZZAVILLE', 'ROMANIA', 'BUCHAREST', 'RUSSIA', 'MOSCOW', 'RWANDA', 'KIGALI', 'SAINT KITTS & NEVIS', 'BASSETERRE', 'SAINT LUCIA', 'CASTRIES', 'SAINT VINCENT & THE GRENADINES', 'KINGSTOWN', 'SAMOA', 'APIA', 'SAN MARINO', 'SAN MARINO', 'SAO TOME & PRÍNCIPE', 'SAO TOME', 'SAUDI ARABIA', 'RIYADH', 'SENEGAL', 'DAKAR', 'SERBIA', 'BELGRADE', 'SEYCHELLES', 'VICTORIA', 'SIERRA LEONE', 'FREETOWN', 'SINGAPORE', 'SINGAPORE', 'SLOVAKIA', 'BRATISLAVA', 'SLOVENIA', 'LJUBLJANA', 'SOLOMON ISLANDS', 'HONIARA', 'SOMALIA\tMOGADISHU', 'SOUTH AFRICA', 'BLOEMFONTEIN', 'CAPE TOWN', 'PRETORIA', 'SOUTH KOREA', 'SEOUL', 'SOUTH SUDAN', 'JUBA', 'SPAIN', 'MADRID', 'SRI LANKA', 'COLOMBO', 'SUDAN', 'KHARTOUM', 'SURINAME', 'PARAMARIBO', 'SWEDEN', 'STOCKHOLM', 'SWITZERLAND', 'BERN', 'SYRIA', 'DAMASCUS', 'TAJIKISTAN', 'DUSHANBE', 'TANZANIA', 'DODOMA', 'THAILAND', 'BANGKOK', 'TIMOR-LESTE', 'DILI', 'TOGO', 'LOME', 'TONGA', 'NUKUʻALOFA', 'TRINIDAD & TOBAGO', 'SPAIN', 'TUNISIA', 'TUNIS', 'TURKEY', 'ANKARA', 'TURKMENISTAN', 'ASHGABAT', 'TUVALU', 'FUNAFUTI', 'UGANDA', 'KAMPALA', 'UKRAINE', 'KIEV', 'UNITED', 'ARAB EMIRATES', 'ABU', 'DHABI', 'UNITED KINGDOM', 'LONDON', 'UNITED STATES', 'WASHINGTON D.C.', 'URUGUAY', 'MONTEVIDEO', 'UZBEKISTAN', 'TASHKENT', 'VANUATU', 'PORT VILA', 'VATICAN CITY', 'VATICAN CITY', 'VENEZUELA', 'CARACAS', 'VIETNAM', 'HANOI', 'YEMEN', "SANA'A", 'ZAMBIA', 'LUSAKA', 'ZIMBABWE']
turn = False
letter = 'S'
c = False
while True:

    print('Say from letter : ' + letter)
    word = input()
    if word[0].upper() == letter:
        c = False
        for i in range(len(places)-1):
            if places[i] == word.upper():                
                c = True
                break

        letter = word[-1]
        print(letter)
        time.sleep(1)
        
        if c == False:
            print("You have lost by wrong word")
            time.sleep(3)
            quit()
        else:
            print("Good, I recognized it")
            print("Thinking...Ahhh")
            time.sleep(2)
            for i in range(len(places) - 2):
                if places[i][0] == word[-1].upper():
                    word = places[i]
                    del places[i]
                    break
            print(random.choice(("I got it!! It's ","Get this... " , "Easy Peasy Lemon Squeezy : ", "Da boring  ","Mind the ",)) + word)
            letter = word[-1]
    else:
        print('Say from letter : ' + letter + '\n')
        word = input('')
            
