a = input("Name of your project please")
print("""Warnings:
1.DO NOT IMPORT PYGAME
2.DO NOT CREATE ANY OTHER FILE THROUGH THIS
3.IF PYGAME IS IMPORTED PLEASE DELETE THE '__pycache__' SUBFOLDER WHICH HAS APPEARED IN THE SAME FOLDER OR THE SAME DIRECTORY
4.DO NOT IMPORT ANY OTHER MODULE WHICH HAS BEEN RECENTLY DOWNLOADED MANUALLY FROM ANY OTHER WEBSITE BESIDES ORGINAL PYTHON WEBSITE
5.WHEN IMPORTING ANY OTHER MODULE WHICH HAS BEEN RECENTLY DOWNLOADED MANUALLY FROM ANY OTHER WEBSITE PLEASE TURN OFF YOUR WI-FI
6.IF VIRUS CAUSED, IMMEDIATELY SHUTDOWN THE COMPUTER OR DELETE ANY OTHER FILE WHICH HAS NOT BEEN DOWNLOADED IN YOUR FOLDER/DESKTOP/SHORTCUT
7.IF A FILE REAPPEARS AFTER DELETING AND HAS NOT BEEN DOWNLOADED RECENTLY PLEASE EMPTY THE RECYCLING BIN AFTER DELETING THE FILE
8.IF THE FILES IN THE SAME FOLDER AS THIS FILE IS IN STOP WORKING OR THREATENING TO CRASH AFTER A MODULE IS IMPORTED PLEASE MAKE SURE NO FILE/FOLDER HAS APPEARED WHICH HASN'T BEEN DOWNLOADED, IF FOUND PLEASE DELETE IT AND EMPTY THE RECYCLING BIN AND DON'T USE THE MODULE AGAIN
9.IF THE SYSTEM IS OVERHEATING OR THREATENING TO CRASH WHILE RUNNING THE PROGRAM PLEASE DELETE IT
10.IF VIRUS COULDN'T BE REMOVED FROM THE COMPUTER AND IS NOW GAINING ACCESS OVER OTHER FILES PLEASE ABANDON THE COMPUTER. """)
try:
    f = open(a + '.py', 'x')
    while True:
        b = input("")
        f.write(b + "\n")
        if b == "":
            break
            
    f = open(a + '.py','a')
    f.close()
    quit()
except FileExistsError:
    f = open(a + '.py','a')
    while True:
        b = input("")
        f.write(b + "\n")
        if b == "":
            break
    f.close()
    quit()
    
